<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE 자동차 [
	<!ELEMENT phone (handphone+) >
	<!ELEMENT handphone (os, name+, price+)>
	<!ELEMENT os (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT price (#PCDATA)>

	<!--
	사용횟수
	 + : 1개 이상
	 * : 0개 이상
	 ? : 0 OR 1 
	 A|B : A 또는 B 둘 중에 하나
	 () : 요소를 그룹으로 선언해서 사용
	-->
]>
<phone>
	<handphone>
		<os>안두로이드</os>
		<name>갤락시</name>
		<name>갤락티카</name>
		<price>500000</price>
	</handphone>

	<handphone>
		<os>에풀</os>
		<name>아이뽀12</name>
		<price>66666</price>
	</handphone>

	<handphone>
		<os>잉도오ㅜ</os>
		<name>잉도폰</name>
		<price>100</price>
	</handphone>
</phone>
